<?php

namespace App\Controllers;

use CodeIgniter\HTTP\RequestInterface;
use CodeIgniter\HTTP\ResponseInterface;
use Psr\Log\LoggerInterface;

class Home extends BaseController
{
    public function initController(RequestInterface $request, ResponseInterface $response, LoggerInterface $logger)
    {
        parent::initController($request, $response, $logger); // TODO: Change the autogenerated stub
    }

    public function index(){
        $session = session();

        $data = [
            'auth'=>$session->get('auth')
        ];

        pr($session->get('loginSecurityKey'));
        pr($session->get('loginSecurityKey')['is_verified']=='');

        return view('Home/index', $data);
    }
}
